AWSTemplateFormatVersion: '2010-09-09'
Description: Route 53 DNS with ARC-controlled health checks

Parameters:
  DomainName:
    Type: String
    Description: Domain name for the API (e.g., api.example.com)
    Default: api-failover-test.example.com

Resources:
  # Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  # Health Check for us-east-1 (powered by ARC)
  HealthCheckEast:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: RECOVERY_CONTROL
        RoutingControlArn: !Sub '{{resolve:ssm:/app-failover/arc-control-us-east-1}}'
      HealthCheckTags:
        - Key: Name
          Value: arc-health-us-east-1

  # Health Check for us-west-2 (powered by ARC)
  HealthCheckWest:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: RECOVERY_CONTROL
        RoutingControlArn: !Sub '{{resolve:ssm:/app-failover/arc-control-us-west-2}}'
      HealthCheckTags:
        - Key: Name
          Value: arc-health-us-west-2

  # DNS Record - Primary (us-east-1)
  DNSRecordPrimary:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      SetIdentifier: us-east-1
      Failover: PRIMARY
      HealthCheckId: !Ref HealthCheckEast
      AliasTarget:
        HostedZoneId: Z1UJRXOUMOOFQ8  # API Gateway hosted zone for us-east-1
        DNSName: !Sub '{{resolve:ssm:/app-failover/api-endpoint-us-east-1}}'
        EvaluateTargetHealth: false

  # DNS Record - Secondary (us-west-2)
  DNSRecordSecondary:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      SetIdentifier: us-west-2
      Failover: SECONDARY
      HealthCheckId: !Ref HealthCheckWest
      AliasTarget:
        HostedZoneId: Z2OJLYMUO9EFXC  # API Gateway hosted zone for us-west-2
        DNSName: !Sub '{{resolve:ssm:/app-failover/api-endpoint-us-west-2}}'
        EvaluateTargetHealth: false

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
  DNSName:
    Value: !Ref DomainName
  NameServers:
    Value: !Join [', ', !GetAtt HostedZone.NameServers]
    Description: Update your domain registrar with these name servers
