AWSTemplateFormatVersion: '2010-09-09'
Description: Transit Gateway Peering between us-east-1 and us-west-2

Parameters:
  PrimaryTGWId:
    Type: String
    Description: Transit Gateway ID from us-east-1
  SecondaryTGWId:
    Type: String
    Description: Transit Gateway ID from us-west-2
  PrimaryRouteTableId:
    Type: String
    Description: Route Table ID from us-east-1
  SecondaryVPCCidr:
    Type: String
    Default: 10.2.0.0/16

Resources:
  TGWPeeringAttachment:
    Type: AWS::EC2::TransitGatewayPeeringAttachment
    Properties:
      TransitGatewayId: !Ref PrimaryTGWId
      PeerTransitGatewayId: !Ref SecondaryTGWId
      PeerRegion: us-west-2
      PeerAccountId: !Ref AWS::AccountId
      Tags:
        - Key: Name
          Value: aurora-failover-tgw-peering

  RouteToSecondary:
    Type: AWS::EC2::Route
    DependsOn: TGWPeeringAttachment
    Properties:
      RouteTableId: !Ref PrimaryRouteTableId
      DestinationCidrBlock: !Ref SecondaryVPCCidr
      TransitGatewayId: !Ref PrimaryTGWId

Outputs:
  PeeringAttachmentId:
    Value: !Ref TGWPeeringAttachment
    Description: Transit Gateway Peering Attachment ID
