AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Global Database Primary Cluster (us-east-1)

Parameters:
  DBUsername:
    Type: String
    Default: dbadmin
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Database master password (min 8 characters)

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: aurora-failover-db-secret
      Description: Aurora database credentials
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}",
          "engine": "postgres",
          "port": 5432,
          "host": ""
        }

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora primary
      SubnetIds:
        - !Sub '{{resolve:ssm:/aurora-failover/private-subnet-1-primary}}'
        - !Sub '{{resolve:ssm:/aurora-failover/private-subnet-2-primary}}'
      Tags:
        - Key: Name
          Value: aurora-failover-subnet-group-primary

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: aurora-postgresql17
      Description: Aurora cluster parameter group
      Parameters:
        rds.force_ssl: 0

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: aurora-failover-primary
      Engine: aurora-postgresql
      EngineVersion: '17.7'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/aurora-failover/aurora-sg-primary}}'
      StorageEncrypted: true  # Uses AWS managed key (aws/rds) by default
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: mon:04:00-mon:05:00
      Tags:
        - Key: GlobalDatabase
          Value: aurora-global-test
        - Key: Role
          Value: Primary
        - Key: Region
          Value: us-east-1

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aurora-failover-primary-instance-1
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-postgresql
      DBInstanceClass: db.r6g.large
      PubliclyAccessible: false

  GlobalCluster:
    Type: AWS::RDS::GlobalCluster
    DependsOn: DBCluster
    Properties:
      GlobalClusterIdentifier: aurora-global-test
      SourceDBClusterIdentifier: !Ref DBCluster

  DBEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /aurora-failover/db-endpoint-primary
      Type: String
      Value: !GetAtt DBCluster.Endpoint.Address

Outputs:
  DBClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: aurora-failover-db-endpoint-primary
  GlobalClusterId:
    Value: !Ref GlobalCluster
    Export:
      Name: aurora-failover-global-cluster
  DBClusterId:
    Value: !Ref DBCluster
