AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Global Database Secondary Cluster (us-west-2)

Parameters:
  GlobalClusterIdentifier:
    Type: String
    Default: aurora-global-test
    Description: Global cluster identifier from primary region

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/aurora-secondary
      TargetKeyId: !Ref KMSKey

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora secondary
      SubnetIds:
        - !Sub '{{resolve:ssm:/aurora-failover/private-subnet-1-secondary}}'
        - !Sub '{{resolve:ssm:/aurora-failover/private-subnet-2-secondary}}'
      Tags:
        - Key: Name
          Value: aurora-failover-subnet-group-secondary

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Family: aurora-postgresql17
      Description: Aurora cluster parameter group
      Parameters:
        rds.force_ssl: 0

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: aurora-failover-secondary
      Engine: aurora-postgresql
      EngineVersion: '17.7'
      GlobalClusterIdentifier: !Ref GlobalClusterIdentifier
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      VpcSecurityGroupIds:
        - !Sub '{{resolve:ssm:/aurora-failover/aurora-sg-secondary}}'
      StorageEncrypted: true
      KmsKeyId: !Ref KMSKey
      Tags:
        - Key: GlobalDatabase
          Value: aurora-global-test
        - Key: Role
          Value: Secondary
        - Key: Region
          Value: us-west-2

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aurora-failover-secondary-instance-1
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-postgresql
      DBInstanceClass: db.r6g.large
      PubliclyAccessible: false

  DBEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /aurora-failover/db-endpoint-secondary
      Type: String
      Value: !GetAtt DBCluster.Endpoint.Address

Outputs:
  DBClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: aurora-failover-db-endpoint-secondary
  DBClusterId:
    Value: !Ref DBCluster
