AWSTemplateFormatVersion: '2010-09-09'
Description: Route 53 Application Recovery Controller (us-east-1)

Resources:
  Cluster:
    Type: AWS::Route53RecoveryControl::Cluster
    Properties:
      Name: AppFailover-Cluster

  ControlPanel:
    Type: AWS::Route53RecoveryControl::ControlPanel
    Properties:
      Name: AppFailover-ControlPanel
      ClusterArn: !Ref Cluster

  RoutingControl1:
    Type: AWS::Route53RecoveryControl::RoutingControl
    Properties:
      Name: AppFailover-us-east-1
      ClusterArn: !Ref Cluster
      ControlPanelArn: !Ref ControlPanel

  RoutingControl2:
    Type: AWS::Route53RecoveryControl::RoutingControl
    Properties:
      Name: AppFailover-us-west-2
      ClusterArn: !Ref Cluster
      ControlPanelArn: !Ref ControlPanel

  ClusterParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app-failover/arc-cluster
      Type: String
      Value: !Ref Cluster

  Control1Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app-failover/arc-control-us-east-1
      Type: String
      Value: !Ref RoutingControl1

  Control2Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /app-failover/arc-control-us-west-2
      Type: String
      Value: !Ref RoutingControl2

Outputs:
  ClusterArn:
    Value: !Ref Cluster
    Export:
      Name: app-failover-arc-cluster
  RoutingControl1Arn:
    Value: !Ref RoutingControl1
    Export:
      Name: app-failover-arc-control-us-east-1
  RoutingControl2Arn:
    Value: !Ref RoutingControl2
    Export:
      Name: app-failover-arc-control-us-west-2
